### PR TITLE
Code Climate maintainability badge

### PR DESCRIPTION
**Pull request by sgerrand**
💁 Code Climate changed their metrics for assessing code quality. As part of this change, the previous badges have broken. This change updates this repository with a maintainability badge.

https://codeclimate.com/blog/a-new-clearer-way-to-understand-code-quality

### CODE REVIEW

**Comment by sldblog** [comment]
:memo: To note, https://api.codeclimate.com/v1/badges/1c86f236e035426453de/maintainability.svg still works for me.

**Comment by sgerrand** [comment]
> I guess it's the redirection that kills the badge?

I believe so.

**Comment by damien** [comment]
Looks like the build is failing due to style violations unrelated to changes in this PR.

**Comment by sldblog** [comment]
Yeah, we should lock `rubocop` in `Gemfile`...

**Pull request merged**
